# Generated by Django 3.1.4 on 2020-12-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('statistical_weight', models.CharField(max_length=300, verbose_name='Склад')),
                ('first_date', models.DateTimeField(verbose_name='Дата изготовления')),
                ('expiration_date', models.DateTimeField(verbose_name='Дата окончания')),
            ],
        ),
    ]
